# Generated by Django 2.2a1 on 2020-12-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
