# Generated by Django 2.2a1 on 2021-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appliedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=8)),
                ('resumepath', models.CharField(max_length=50)),
            ],
        ),
    ]
