# Generated by Django 2.2a1 on 2021-04-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvmanager', '0002_applieddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='applieddetail',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applieddetail',
            name='resumepath',
            field=models.FileField(upload_to='media'),
        ),
    ]
