# Generated by Django 2.2a1 on 2021-04-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvmanager', '0003_auto_20210424_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobdesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmingL', models.CharField(max_length=60)),
                ('database', models.CharField(max_length=60)),
                ('frameworks', models.CharField(max_length=60)),
                ('Experience', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=40)),
                ('batch', models.CharField(max_length=50)),
                ('registrationstart', models.CharField(max_length=50)),
                ('registrationend', models.CharField(max_length=50)),
            ],
        ),
    ]
