# Generated by Django 2.2a1 on 2021-04-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvmanager', '0004_jobdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdesc',
            name='cid',
            field=models.CharField(default='itsdefaultvalue', max_length=30),
        ),
    ]
