# Generated by Django 2.2a1 on 2021-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvmanager', '0005_jobdesc_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='queryform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=60)),
            ],
        ),
    ]
